config/routes.rb
Rails.application.routes.draw do

  resources :group_components
  resources :subscriptions
  resources :prices
  resources :users
  #resources :profiles
  resources :components

  root :to => 'home#index'

  get '/signup' => 'users#new'
  get '/i_:username', to: 'profiles#show', as: :profile_show
  get '/i_:username/edit', to: 'profiles#edit', as: :profile_edit
  post '/i_:username/edit', to: 'profiles#update'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/group_component.rb
class GroupComponent < ActiveRecord::Base
  belongs_to :user
  has_many :components
end

app/controllers/group_components_controller.rb
class GroupComponentsController < ApplicationController
  before_action :set_group_component, only: [:show, :edit, :update, :destroy]

  # GET /group_components
  # GET /group_components.json
  def index
    @group_components = GroupComponent.all.where( :user_id => current_user.id )
  end

  # GET /group_components/1
  # GET /group_components/1.json
  def show
  end

  # GET /group_components/new
  def new
    @group_component = GroupComponent.new
  end

  # GET /group_components/1/edit
  def edit
  end

  # POST /group_components
  # POST /group_components.json
  def create
    @group_component = GroupComponent.new(:user_id => current_user.id,
                                          :name => group_component_params[:name],
                                          :description => group_component_params[:description],
                                          :enable => group_component_params[:enable])

    respond_to do |format|
      if @group_component.save
        format.html { redirect_to @group_component, notice: 'Group component was successfully created.' }
        format.json { render :show, status: :created, location: @group_component }
      else
        format.html { render :new }
        format.json { render json: @group_component.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_components/1
  # PATCH/PUT /group_components/1.json
  def update
    respond_to do |format|
      if @group_component.update(group_component_params)
        format.html { redirect_to @group_component, notice: 'Group component was successfully updated.' }
        format.json { render :show, status: :ok, location: @group_component }
      else
        format.html { render :edit }
        format.json { render json: @group_component.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_components/1
  # DELETE /group_components/1.json
  def destroy
    @group_component.destroy
    respond_to do |format|
      format.html { redirect_to group_components_url, notice: 'Group component was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_component
      @group_component = GroupComponent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_component_params
      params.require(:group_component).permit(:name, :description, :enable)
    end
end

app/helpers/group_components_helper.rb
module GroupComponentsHelper
end

app/views/group_components/_form.html.erb
<%= form_for(@group_component) do |f| %>
  <% if @group_component.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group_component.errors.count, "error") %> prohibited this group_component from being saved:</h2>

      <ul>
      <% @group_component.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :enable %><br>
    <%= f.check_box :enable, :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-success" %>
  </div>
<% end %>

app/views/group_components/edit.html.erb
<h1>Editing Group Component</h1>

<%= render 'form' %>

<%= link_to 'Show', @group_component, :class => "btn btn-primary" %> |
<%= link_to 'Back', group_components_path, :class => "btn btn-danger" %>

app/views/group_components/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Group Components</h1>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Description</th>
      <th>Enable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @group_components.each do |group_component| %>
      <tr>
        <td><%= group_component.user_id %></td>
        <td><%= group_component.name %></td>
        <td><%= group_component.description %></td>
        <td><%= group_component.enable %></td>
        <td><%= link_to 'Show', group_component,:class => "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_group_component_path(group_component), :class => "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', group_component, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_group_component_path, class: 'btn btn-success' do %>
    <i class="glyphicon glyphicon-plus"></i> New Group Component
<% end %>

app/views/group_components/new.html.erb
<h1>New Group Component</h1>

<%= render 'form' %>

<%= link_to 'Back', group_components_path, :class => "btn btn-danger" %>

app/views/group_components/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @group_component.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @group_component.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group_component.description %>
</p>

<p>
  <strong>Enable:</strong>
  <%= @group_component.enable %>
</p>

<%= link_to 'Edit', edit_group_component_path(@group_component), :class => "btn btn-primary" %> |
<%= link_to 'Back', group_components_path, :class => "btn btn-danger" %>