config/routes.rb
Rails.application.routes.draw do

  resources :group_components
  resources :subscriptions
  resources :prices
  resources :users
  #resources :profiles
  resources :components

  root :to => 'home#index'

  get '/signup' => 'users#new'
  get '/i_:username', to: 'profiles#show', as: :profile_show
  get '/i_:username/edit', to: 'profiles#edit', as: :profile_edit
  post '/i_:username/edit', to: 'profiles#update'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  has_many :profiles
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:name, :name_with_price, :value, :currency, :color, :group, :enable)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :name_with_price %><br>
    <%= f.text_field :name_with_price, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :value %><br>
    <%= f.text_field :value, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :currency %><br>
    <%= f.text_field :currency, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :color %><br>
    <%= f.text_field :color, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :group %><br>
    <%= f.text_field :group, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :enable %><br>
    <%= f.check_box :enable, :class => "form-control"%>
  </div>
  <div class="form-group">
    <%= f.submit :class => "btn btn-success"%>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription, :class => "btn btn-primary" %> |
<%= link_to 'Back', subscriptions_path, :class => "btn btn-danger" %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subscriptions</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Name with price</th>
      <th>Value</th>
      <th>Currency</th>
      <th>Color</th>
      <th>Group</th>
      <th>Enable</th>
      <th colspan="3"> Options</th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.name %></td>
        <td><%= subscription.name_with_price %></td>
        <td><%= subscription.value %></td>
        <td><%= subscription.currency %></td>
        <td><%= subscription.color %></td>
        <td><%= subscription.group %></td>
        <td><%= subscription.enable %></td>
        <td><%= link_to 'Show', subscription, :class => "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription), :class => "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_subscription_path, class: 'btn btn-success' do %>
    <i class="glyphicon glyphicon-plus"></i> New Subscription
<% end %>

app/views/subscriptions/new.html.erb
<h1>New Subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path, :class => "btn btn-danger" %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subscription.name %>
</p>

<p>
  <strong>Name with price:</strong>
  <%= @subscription.name_with_price %>
</p>

<p>
  <strong>Value:</strong>
  <%= @subscription.value %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @subscription.currency %>
</p>

<p>
  <strong>Color:</strong>
  <%= @subscription.color %>
</p>

<p>
  <strong>Group:</strong>
  <%= @subscription.group %>
</p>

<p>
  <strong>Enable:</strong>
  <%= @subscription.enable %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription), :class => "btn btn-primary" %> |
<%= link_to 'Back', subscriptions_path, :class => "btn btn-danger" %>