config/routes.rb
Rails.application.routes.draw do

  resources :group_components
  resources :subscriptions
  resources :prices
  resources :users
  #resources :profiles
  resources :components

  root :to => 'home#index'

  get '/signup' => 'users#new'
  get '/i_:username', to: 'profiles#show', as: :profile_show
  get '/i_:username/edit', to: 'profiles#edit', as: :profile_edit
  post '/i_:username/edit', to: 'profiles#update'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/price.rb
class Price < ActiveRecord::Base
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]

  # GET /prices
  # GET /prices.json
  def index
    @prices = Price.all
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(price_params)

    respond_to do |format|
      if @price.save
        format.html { redirect_to @price, notice: 'Price was successfully created.' }
        format.json { render :show, status: :created, location: @price }
      else
        format.html { render :new }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    respond_to do |format|
      if @price.update(price_params)
        format.html { redirect_to @price, notice: 'Price was successfully updated.' }
        format.json { render :show, status: :ok, location: @price }
      else
        format.html { render :edit }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html { redirect_to prices_url, notice: 'Price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_params
      params.require(:price).permit(:name, :name_with_price, :value, :currency, :color, :group, :enable)
    end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_form.html.erb
<%= form_for(@price) do |f| %>
  <% if @price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
      <% @price.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :name_with_price %><br>
    <%= f.text_field :name_with_price, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :value %><br>
    <%= f.text_field :value, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :currency %><br>
    <%= f.text_field :currency, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :color %><br>
    <%= f.text_field :color, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :group %><br>
    <%= f.text_field :group, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :enable %><br>
    <%= f.check_box :enable, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit :class => "btn btn-success"%>
  </div>
<% end %>

app/views/prices/edit.html.erb
<h1>Editing Price</h1>

<%= render 'form' %>

<%= link_to 'Show', @price, :class => "btn btn-primary" %> |
<%= link_to 'Back', prices_path, :class => "btn btn-danger" %>

app/views/prices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Prices</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Name with price</th>
      <th>Value</th>
      <th>Currency</th>
      <th>Color</th>
      <th>Group</th>
      <th>Enable</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @prices.each do |price| %>
      <tr>
        <td><%= price.name %></td>
        <td><%= price.name_with_price %></td>
        <td><%= price.value %></td>
        <td><%= price.currency %></td>
        <td><%= price.color %></td>
        <td><%= price.group %></td>
        <td><%= price.enable %></td>
        <td><%= link_to 'Show', price, class: 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_price_path(price), class: 'btn btn-primary' %></td>
        <td><%= link_to 'Destroy', price, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_price_path, class: 'btn btn-success' do %>
    <i class="glyphicon glyphicon-plus"></i> New Price
<% end %>

app/views/prices/new.html.erb
<h1>New Price</h1>

<%= render 'form' %>

<%= link_to 'Back', prices_path, :class => "btn btn-danger" %>

app/views/prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @price.name %>
</p>

<p>
  <strong>Name with price:</strong>
  <%= @price.name_with_price %>
</p>

<p>
  <strong>Value:</strong>
  <%= @price.value %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @price.currency %>
</p>

<p>
  <strong>Color:</strong>
  <%= @price.color %>
</p>

<p>
  <strong>Group:</strong>
  <%= @price.group %>
</p>

<p>
  <strong>Enable:</strong>
  <%= @price.enable %>
</p>

<%= link_to 'Edit', edit_price_path(@price), :class => "btn btn-primary" %> |
<%= link_to 'Back', prices_path, :class => "btn btn-danger" %>